Feat cylc template
WilhelmusLab/IceFloeTracker.jl pull request #289
Opened 2023-05-12 20:44 UTC by tdivoll

This PR sets the framework to run the IceFloeTracker tasks in a Cylc pipeline. For now, we run the pipeline one, but using Cylc allows for cycling and more complicated workflows in the future.

2023-05-24 14:54 UTC, tdivoll commented
I believe all the Register files were caught by the formatter.

2023-05-24 17:58 UTC, cpaniaguam requested changes
👍   Couple of comments about removing snakemake vestiges and dangling end-of-line at the end of non-,jl files.

2023-05-24 17:58 UTC, cpaniaguam commented on scripts/pass_time_snakemake.py
If snakemake is not going to be used anymore, renaming this file might be sensible.

2023-05-24 17:58 UTC, cpaniaguam commented on scripts/Dockerfile
> +ENTRYPOINT bash
```suggestion
ENTRYPOINT bash

```

2023-05-24 17:58 UTC, cpaniaguam commented on cylc/flow.cylc
> +        """
```suggestion
        """
        
```

2023-05-25 18:03 UTC, broarr approved these changes
Looks good to me! Most of these changes are just format changes right?

2023-05-25 20:34 UTC, tdivoll commented on .github/workflows/build-docker.yml
> +          password: ${{ secrets.GITHUB_TOKEN }}
I will play with that, it makes sense for software that will be open-sourced anyways

2023-05-25 20:35 UTC, tdivoll commented on scripts/Dockerfile
> +ENTRYPOINT bash
That is correct! In the cylc pipeline I have one task each to call both of the scripts.

2023-05-26 20:31 UTC, closed without merging

2023-05-26 20:32 UTC, tdivoll commented
Replaced by #297 and by https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/pull/13